// Decompiled with JetBrains decompiler
// Type: KSWB.TestControl
// Assembly: KSWB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 99F4CEBB-9EF3-4B2B-95A0-A11E98E61BA0
// Assembly location: C:\Program Files (x86)\CYP\KSWB.exe

using KSWB.Properties;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace KSWB
{
  public class TestControl : UserControl
  {
    private IContainer components;
    private TabControl tcCrops;
    private TabPage tpGeneral;
    private Label label21;
    public GroupBox groupBox3;
    private Button btnAlf;
    private Button button2;
    public DataGridView dgCoefficients;
    public Label label5;
    public GroupBox groupBox2;
    private Button button5;
    private TextBox txtMaxYield;
    private Label label13;
    private Label lblMaxYield;
    public ListBox lstCrops;
    public Label label10;
    private TabPage tpIrrigation;
    private GroupBox groupBox8;
    private TabControl tabControl1;
    private TabPage tpIrrigationEntries;
    private Label label8;
    private Label lblwheat;
    private DataGridView dgIrrigation;
    private Button button1;
    public Label label2;
    public Label label1;
    private TabPage tabPage1;
    private Button button3;
    private Label label14;
    private Label lblAuto;
    private TextBox txtAuto;
    private Label lblAutoUnits;
    private GroupBox groupBox1;
    private RadioButton rbNetIrrigation;
    private RadioButton rbGPM;
    private Label label12;
    private Button cmdAuto;
    private TextBox txtAcres;
    private DateTimePicker dteIrrigEnd;
    private Label label9;
    private Label label7;
    private TextBox txtInchesPerApplication;
    private Label label6;
    private Label label4;
    private DateTimePicker dteIrrigStart;
    private Label label3;
    private TabPage tpCosts;
    public GroupBox groupBox4;
    private Label label15;
    private TextBox textBox1;
    private Label label26;
    private TabControl tpInputCosts;
    private TabPage tabPage2;
    private DataGridView dgGeneralCosts;
    private TabPage tabPage3;
    private DataGridView dgOperationCosts;
    private TabPage tabPage4;
    private DataGridView dgReturns;
    private TabPage tabPage5;
    private ComboBox comboBox1;
    private Label label17;
    private DataGridView dgIrrigationCosts;
    private TextBox txtPrice;
    private Label label11;
    private Label lblPriceUnits;
    public Label label16;

    public TestControl()
    {
      this.InitializeComponent();
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.tcCrops = new TabControl();
      this.tpGeneral = new TabPage();
      this.label21 = new Label();
      this.groupBox3 = new GroupBox();
      this.btnAlf = new Button();
      this.button2 = new Button();
      this.dgCoefficients = new DataGridView();
      this.label5 = new Label();
      this.groupBox2 = new GroupBox();
      this.button5 = new Button();
      this.txtMaxYield = new TextBox();
      this.label13 = new Label();
      this.lblMaxYield = new Label();
      this.lstCrops = new ListBox();
      this.label10 = new Label();
      this.tpIrrigation = new TabPage();
      this.groupBox8 = new GroupBox();
      this.tabControl1 = new TabControl();
      this.tpIrrigationEntries = new TabPage();
      this.label8 = new Label();
      this.lblwheat = new Label();
      this.dgIrrigation = new DataGridView();
      this.button1 = new Button();
      this.label2 = new Label();
      this.label1 = new Label();
      this.tabPage1 = new TabPage();
      this.button3 = new Button();
      this.label14 = new Label();
      this.lblAuto = new Label();
      this.txtAuto = new TextBox();
      this.lblAutoUnits = new Label();
      this.groupBox1 = new GroupBox();
      this.rbNetIrrigation = new RadioButton();
      this.rbGPM = new RadioButton();
      this.label12 = new Label();
      this.cmdAuto = new Button();
      this.txtAcres = new TextBox();
      this.dteIrrigEnd = new DateTimePicker();
      this.label9 = new Label();
      this.label7 = new Label();
      this.txtInchesPerApplication = new TextBox();
      this.label6 = new Label();
      this.label4 = new Label();
      this.dteIrrigStart = new DateTimePicker();
      this.label3 = new Label();
      this.tpCosts = new TabPage();
      this.groupBox4 = new GroupBox();
      this.label15 = new Label();
      this.textBox1 = new TextBox();
      this.label26 = new Label();
      this.tpInputCosts = new TabControl();
      this.tabPage2 = new TabPage();
      this.dgGeneralCosts = new DataGridView();
      this.tabPage3 = new TabPage();
      this.dgOperationCosts = new DataGridView();
      this.tabPage4 = new TabPage();
      this.dgReturns = new DataGridView();
      this.tabPage5 = new TabPage();
      this.comboBox1 = new ComboBox();
      this.label17 = new Label();
      this.dgIrrigationCosts = new DataGridView();
      this.txtPrice = new TextBox();
      this.label11 = new Label();
      this.lblPriceUnits = new Label();
      this.label16 = new Label();
      this.tcCrops.SuspendLayout();
      this.tpGeneral.SuspendLayout();
      this.groupBox3.SuspendLayout();
      ((ISupportInitialize) this.dgCoefficients).BeginInit();
      this.groupBox2.SuspendLayout();
      this.tpIrrigation.SuspendLayout();
      this.groupBox8.SuspendLayout();
      this.tabControl1.SuspendLayout();
      this.tpIrrigationEntries.SuspendLayout();
      ((ISupportInitialize) this.dgIrrigation).BeginInit();
      this.tabPage1.SuspendLayout();
      this.groupBox1.SuspendLayout();
      this.tpCosts.SuspendLayout();
      this.groupBox4.SuspendLayout();
      this.tpInputCosts.SuspendLayout();
      this.tabPage2.SuspendLayout();
      ((ISupportInitialize) this.dgGeneralCosts).BeginInit();
      this.tabPage3.SuspendLayout();
      ((ISupportInitialize) this.dgOperationCosts).BeginInit();
      this.tabPage4.SuspendLayout();
      ((ISupportInitialize) this.dgReturns).BeginInit();
      this.tabPage5.SuspendLayout();
      ((ISupportInitialize) this.dgIrrigationCosts).BeginInit();
      this.SuspendLayout();
      this.tcCrops.Appearance = TabAppearance.Buttons;
      this.tcCrops.Controls.Add((Control) this.tpGeneral);
      this.tcCrops.Controls.Add((Control) this.tpIrrigation);
      this.tcCrops.Controls.Add((Control) this.tpCosts);
      this.tcCrops.Dock = DockStyle.Fill;
      this.tcCrops.Font = new Font("Tahoma", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tcCrops.Location = new Point(0, 0);
      this.tcCrops.Name = "tcCrops";
      this.tcCrops.Padding = new Point(0, 0);
      this.tcCrops.SelectedIndex = 0;
      this.tcCrops.Size = new Size(391, 310);
      this.tcCrops.TabIndex = 18;
      this.tpGeneral.AutoScroll = true;
      this.tpGeneral.BackColor = Color.White;
      this.tpGeneral.Controls.Add((Control) this.label21);
      this.tpGeneral.Controls.Add((Control) this.groupBox3);
      this.tpGeneral.Controls.Add((Control) this.groupBox2);
      this.tpGeneral.ImageIndex = 0;
      this.tpGeneral.Location = new Point(4, 28);
      this.tpGeneral.Name = "tpGeneral";
      this.tpGeneral.Size = new Size(383, 278);
      this.tpGeneral.TabIndex = 0;
      this.tpGeneral.Text = "Crop Selection";
      this.tpGeneral.UseVisualStyleBackColor = true;
      this.label21.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label21.ForeColor = Color.Maroon;
      this.label21.Location = new Point(9, 285);
      this.label21.Name = "label21";
      this.label21.Size = new Size(349, 56);
      this.label21.TabIndex = 19;
      this.label21.Text = "Adjusting crops or growth stage dates will affect the default Runoff coefficient.  Be sure to visit the Runoff && Soil Water tab if an alternate coefficient is desired.";
      this.groupBox3.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox3.Controls.Add((Control) this.btnAlf);
      this.groupBox3.Controls.Add((Control) this.button2);
      this.groupBox3.Controls.Add((Control) this.dgCoefficients);
      this.groupBox3.Controls.Add((Control) this.label5);
      this.groupBox3.ForeColor = Color.SteelBlue;
      this.groupBox3.Location = new Point(3, 117);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(357, 165);
      this.groupBox3.TabIndex = 18;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "Growth Stage Dates";
      this.btnAlf.Location = new Point(6, 89);
      this.btnAlf.Name = "btnAlf";
      this.btnAlf.Size = new Size(142, 24);
      this.btnAlf.TabIndex = 25;
      this.btnAlf.Text = "Delete 5th Cutting";
      this.btnAlf.UseVisualStyleBackColor = true;
      this.btnAlf.Visible = false;
      this.button2.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.button2.ForeColor = Color.RoyalBlue;
      this.button2.Location = new Point(220, 15);
      this.button2.Name = "button2";
      this.button2.Size = new Size(28, 23);
      this.button2.TabIndex = 24;
      this.button2.Text = "?";
      this.button2.UseVisualStyleBackColor = true;
      this.dgCoefficients.AllowUserToAddRows = false;
      this.dgCoefficients.AllowUserToDeleteRows = false;
      this.dgCoefficients.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.dgCoefficients.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
      this.dgCoefficients.BackgroundColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.dgCoefficients.BorderStyle = BorderStyle.None;
      this.dgCoefficients.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgCoefficients.Location = new Point(254, 14);
      this.dgCoefficients.Name = "dgCoefficients";
      this.dgCoefficients.Size = new Size(97, 147);
      this.dgCoefficients.TabIndex = 3;
      this.label5.BackColor = Color.Transparent;
      this.label5.ForeColor = Color.FromArgb(64, 64, 64);
      this.label5.Location = new Point(6, 18);
      this.label5.Name = "label5";
      this.label5.Size = new Size(184, 82);
      this.label5.TabIndex = 2;
      this.label5.Text = "The growth stage dates are show in the list on the right.  Select a date from the list to edit it.";
      this.groupBox2.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox2.BackColor = Color.White;
      this.groupBox2.Controls.Add((Control) this.button5);
      this.groupBox2.Controls.Add((Control) this.txtMaxYield);
      this.groupBox2.Controls.Add((Control) this.label13);
      this.groupBox2.Controls.Add((Control) this.lblMaxYield);
      this.groupBox2.Controls.Add((Control) this.lstCrops);
      this.groupBox2.Controls.Add((Control) this.label10);
      this.groupBox2.ForeColor = Color.SteelBlue;
      this.groupBox2.Location = new Point(3, 3);
      this.groupBox2.Margin = new Padding(0);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Padding = Settings.Default.DefaultPadding2;
      this.groupBox2.Size = new Size(357, 113);
      this.groupBox2.TabIndex = 17;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Crop Type";
      this.button5.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.button5.ForeColor = Color.RoyalBlue;
      this.button5.Location = new Point(220, 18);
      this.button5.Name = "button5";
      this.button5.Size = new Size(28, 23);
      this.button5.TabIndex = 23;
      this.button5.Text = "?";
      this.button5.UseVisualStyleBackColor = true;
      this.txtMaxYield.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.txtMaxYield.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMaxYield.Location = new Point(104, 67);
      this.txtMaxYield.Name = "txtMaxYield";
      this.txtMaxYield.Size = new Size(67, 22);
      this.txtMaxYield.TabIndex = 21;
      this.label13.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label13.ForeColor = Color.FromArgb(64, 64, 64);
      this.label13.Location = new Point(3, 67);
      this.label13.Margin = new Padding(0);
      this.label13.Name = "label13";
      this.label13.Size = new Size(97, 14);
      this.label13.TabIndex = 22;
      this.label13.Text = "Maximum Yield";
      this.label13.TextAlign = ContentAlignment.TopRight;
      this.lblMaxYield.AutoSize = true;
      this.lblMaxYield.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblMaxYield.ForeColor = Color.FromArgb(64, 64, 64);
      this.lblMaxYield.Location = new Point(172, 67);
      this.lblMaxYield.Name = "lblMaxYield";
      this.lblMaxYield.Size = new Size(15, 14);
      this.lblMaxYield.TabIndex = 20;
      this.lblMaxYield.Text = "--";
      this.lstCrops.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.lstCrops.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.lstCrops.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lstCrops.FormattingEnabled = true;
      this.lstCrops.Items.AddRange(new object[1]
      {
        (object) "No crops loaded yet..."
      });
      this.lstCrops.Location = new Point(251, 18);
      this.lstCrops.Name = "lstCrops";
      this.lstCrops.Size = new Size(103, 82);
      this.lstCrops.TabIndex = 10;
      this.label10.BackColor = Color.Transparent;
      this.label10.ForeColor = Color.FromArgb(64, 64, 64);
      this.label10.Location = new Point(9, 21);
      this.label10.Margin = new Padding(0);
      this.label10.Name = "label10";
      this.label10.Size = new Size(208, 43);
      this.label10.TabIndex = 1;
      this.label10.Text = "Available crops for the simulation are listed in the box to the right.";
      this.tpIrrigation.AutoScroll = true;
      this.tpIrrigation.Controls.Add((Control) this.groupBox8);
      this.tpIrrigation.ImageIndex = 0;
      this.tpIrrigation.Location = new Point(4, 28);
      this.tpIrrigation.Name = "tpIrrigation";
      this.tpIrrigation.Size = new Size(484, 380);
      this.tpIrrigation.TabIndex = 2;
      this.tpIrrigation.Text = "Irrigation Schedule";
      this.tpIrrigation.UseVisualStyleBackColor = true;
      this.groupBox8.BackColor = Color.White;
      this.groupBox8.Controls.Add((Control) this.tabControl1);
      this.groupBox8.Dock = DockStyle.Fill;
      this.groupBox8.Location = new Point(0, 0);
      this.groupBox8.Name = "groupBox8";
      this.groupBox8.Padding = new Padding(0);
      this.groupBox8.Size = new Size(484, 380);
      this.groupBox8.TabIndex = 16;
      this.groupBox8.TabStop = false;
      this.groupBox8.Text = "Irrigation Events";
      this.tabControl1.Controls.Add((Control) this.tpIrrigationEntries);
      this.tabControl1.Controls.Add((Control) this.tabPage1);
      this.tabControl1.Location = new Point(9, 22);
      this.tabControl1.Name = "tabControl1";
      this.tabControl1.Padding = new Point(0, 0);
      this.tabControl1.SelectedIndex = 0;
      this.tabControl1.Size = new Size(452, 340);
      this.tabControl1.TabIndex = 5;
      this.tpIrrigationEntries.Controls.Add((Control) this.label8);
      this.tpIrrigationEntries.Controls.Add((Control) this.lblwheat);
      this.tpIrrigationEntries.Controls.Add((Control) this.dgIrrigation);
      this.tpIrrigationEntries.Controls.Add((Control) this.button1);
      this.tpIrrigationEntries.Controls.Add((Control) this.label2);
      this.tpIrrigationEntries.Controls.Add((Control) this.label1);
      this.tpIrrigationEntries.Location = new Point(4, 25);
      this.tpIrrigationEntries.Name = "tpIrrigationEntries";
      this.tpIrrigationEntries.Size = new Size(444, 311);
      this.tpIrrigationEntries.TabIndex = 0;
      this.tpIrrigationEntries.Text = "Gross Irrigation Entries";
      this.tpIrrigationEntries.UseVisualStyleBackColor = true;
      this.label8.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label8.ForeColor = Color.Maroon;
      this.label8.Location = new Point(3, 81);
      this.label8.Name = "label8";
      this.label8.Size = new Size(219, 82);
      this.label8.TabIndex = 13;
      this.label8.Text = "For each irrigation event no more than 2 inches of net irrigation can infiltrate into the soil. Excess irrigation is considered runoff in the soil water balance. ";
      this.label8.Visible = false;
      this.lblwheat.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblwheat.ForeColor = Color.Maroon;
      this.lblwheat.Location = new Point(3, 173);
      this.lblwheat.Name = "lblwheat";
      this.lblwheat.Size = new Size(219, 53);
      this.lblwheat.TabIndex = 12;
      this.lblwheat.Text = "Gross irrigation amounts entered for Winter Wheat will be applied in the year the crop is harvested.";
      this.lblwheat.Visible = false;
      this.dgIrrigation.BackgroundColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.dgIrrigation.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgIrrigation.Location = new Point(227, 34);
      this.dgIrrigation.Name = "dgIrrigation";
      this.dgIrrigation.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
      this.dgIrrigation.ShowCellErrors = false;
      this.dgIrrigation.ShowRowErrors = false;
      this.dgIrrigation.Size = new Size(211, 222);
      this.dgIrrigation.TabIndex = 0;
      this.button1.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.button1.Location = new Point(115, 229);
      this.button1.Name = "button1";
      this.button1.Size = new Size(106, 27);
      this.button1.TabIndex = 1;
      this.button1.Text = "Paste from Excel";
      this.button1.UseVisualStyleBackColor = true;
      this.label2.BackColor = Color.Transparent;
      this.label2.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.ForeColor = Color.FromArgb(64, 64, 64);
      this.label2.Location = new Point(3, 49);
      this.label2.Name = "label2";
      this.label2.Size = new Size(218, 38);
      this.label2.TabIndex = 3;
      this.label2.Text = "Date format: m/d (example 7/3 represents July 3)";
      this.label1.BackColor = Color.Transparent;
      this.label1.ForeColor = Color.FromArgb(64, 64, 64);
      this.label1.Location = new Point(3, 0);
      this.label1.Name = "label1";
      this.label1.Size = new Size(209, 34);
      this.label1.TabIndex = 2;
      this.label1.Text = "Enter gross irrigation amounts into the table. ";
      this.tabPage1.AutoScroll = true;
      this.tabPage1.Controls.Add((Control) this.button3);
      this.tabPage1.Controls.Add((Control) this.label14);
      this.tabPage1.Controls.Add((Control) this.lblAuto);
      this.tabPage1.Controls.Add((Control) this.txtAuto);
      this.tabPage1.Controls.Add((Control) this.lblAutoUnits);
      this.tabPage1.Controls.Add((Control) this.groupBox1);
      this.tabPage1.Controls.Add((Control) this.label12);
      this.tabPage1.Controls.Add((Control) this.cmdAuto);
      this.tabPage1.Controls.Add((Control) this.txtAcres);
      this.tabPage1.Controls.Add((Control) this.dteIrrigEnd);
      this.tabPage1.Controls.Add((Control) this.label9);
      this.tabPage1.Controls.Add((Control) this.label7);
      this.tabPage1.Controls.Add((Control) this.txtInchesPerApplication);
      this.tabPage1.Controls.Add((Control) this.label6);
      this.tabPage1.Controls.Add((Control) this.label4);
      this.tabPage1.Controls.Add((Control) this.dteIrrigStart);
      this.tabPage1.Controls.Add((Control) this.label3);
      this.tabPage1.Location = new Point(4, 22);
      this.tabPage1.Margin = new Padding(0);
      this.tabPage1.Name = "tabPage1";
      this.tabPage1.Size = new Size(444, 314);
      this.tabPage1.TabIndex = 2;
      this.tabPage1.Text = "Uniform Frequency of Irrigation Events";
      this.tabPage1.UseVisualStyleBackColor = true;
      this.button3.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.button3.ForeColor = Color.RoyalBlue;
      this.button3.Location = new Point(316, 6);
      this.button3.Margin = new Padding(0);
      this.button3.Name = "button3";
      this.button3.Size = new Size(28, 23);
      this.button3.TabIndex = 59;
      this.button3.Text = "?";
      this.button3.UseVisualStyleBackColor = true;
      this.label14.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label14.ForeColor = Color.FromArgb(64, 64, 64);
      this.label14.Location = new Point(81, 158);
      this.label14.Margin = new Padding(0);
      this.label14.Name = "label14";
      this.label14.Size = new Size(158, 14);
      this.label14.TabIndex = 58;
      this.label14.Text = "Acres";
      this.label14.TextAlign = ContentAlignment.TopRight;
      this.lblAuto.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblAuto.ForeColor = Color.FromArgb(64, 64, 64);
      this.lblAuto.Location = new Point(70, 134);
      this.lblAuto.Margin = new Padding(0);
      this.lblAuto.Name = "lblAuto";
      this.lblAuto.Size = new Size(169, 14);
      this.lblAuto.TabIndex = 57;
      this.lblAuto.Text = "Pump capacity";
      this.lblAuto.TextAlign = ContentAlignment.TopRight;
      this.txtAuto.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.txtAuto.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtAuto.Location = new Point(246, 132);
      this.txtAuto.Margin = new Padding(0);
      this.txtAuto.Name = "txtAuto";
      this.txtAuto.Size = new Size(60, 22);
      this.txtAuto.TabIndex = 56;
      this.txtAuto.WordWrap = false;
      this.lblAutoUnits.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblAutoUnits.ForeColor = Color.FromArgb(64, 64, 64);
      this.lblAutoUnits.Location = new Point(313, 134);
      this.lblAutoUnits.Margin = new Padding(0);
      this.lblAutoUnits.Name = "lblAutoUnits";
      this.lblAutoUnits.Size = new Size(31, 14);
      this.lblAutoUnits.TabIndex = 55;
      this.lblAutoUnits.Text = "GPM";
      this.lblAutoUnits.TextAlign = ContentAlignment.TopRight;
      this.groupBox1.Controls.Add((Control) this.rbNetIrrigation);
      this.groupBox1.Controls.Add((Control) this.rbGPM);
      this.groupBox1.Location = new Point(30, 63);
      this.groupBox1.Margin = new Padding(0);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(387, 66);
      this.groupBox1.TabIndex = 54;
      this.groupBox1.TabStop = false;
      this.rbNetIrrigation.AutoSize = true;
      this.rbNetIrrigation.Location = new Point(7, 39);
      this.rbNetIrrigation.Margin = new Padding(0);
      this.rbNetIrrigation.Name = "rbNetIrrigation";
      this.rbNetIrrigation.Size = new Size(331, 20);
      this.rbNetIrrigation.TabIndex = 33;
      this.rbNetIrrigation.Text = "Create schedule based on the Total Season Irrigation";
      this.rbNetIrrigation.UseVisualStyleBackColor = true;
      this.rbGPM.AutoSize = true;
      this.rbGPM.Checked = true;
      this.rbGPM.Location = new Point(7, 13);
      this.rbGPM.Margin = new Padding(0);
      this.rbGPM.Name = "rbGPM";
      this.rbGPM.Size = new Size(203, 20);
      this.rbGPM.TabIndex = 32;
      this.rbGPM.TabStop = true;
      this.rbGPM.Text = "Create schedule based on GPM";
      this.rbGPM.UseVisualStyleBackColor = true;
      this.label12.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label12.ForeColor = Color.FromArgb(64, 64, 64);
      this.label12.Location = new Point(317, 180);
      this.label12.Margin = new Padding(0);
      this.label12.Name = "label12";
      this.label12.Size = new Size(41, 14);
      this.label12.TabIndex = 53;
      this.label12.Text = "inches";
      this.cmdAuto.Location = new Point(73, 219);
      this.cmdAuto.Margin = new Padding(0);
      this.cmdAuto.Name = "cmdAuto";
      this.cmdAuto.Size = new Size(310, 24);
      this.cmdAuto.TabIndex = 42;
      this.cmdAuto.Text = "Create gross irrigation events table";
      this.cmdAuto.UseVisualStyleBackColor = true;
      this.txtAcres.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.txtAcres.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtAcres.Location = new Point(246, 156);
      this.txtAcres.Margin = new Padding(0);
      this.txtAcres.Name = "txtAcres";
      this.txtAcres.Size = new Size(60, 22);
      this.txtAcres.TabIndex = 50;
      this.dteIrrigEnd.Format = DateTimePickerFormat.Short;
      this.dteIrrigEnd.Location = new Point(316, 36);
      this.dteIrrigEnd.Margin = new Padding(0);
      this.dteIrrigEnd.Name = "dteIrrigEnd";
      this.dteIrrigEnd.Size = new Size(101, 23);
      this.dteIrrigEnd.TabIndex = 44;
      this.label9.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label9.ForeColor = Color.FromArgb(64, 64, 64);
      this.label9.Location = new Point(317, 158);
      this.label9.Margin = new Padding(0);
      this.label9.Name = "label9";
      this.label9.Size = new Size(37, 14);
      this.label9.TabIndex = 49;
      this.label9.Text = "Acres";
      this.label9.TextAlign = ContentAlignment.TopRight;
      this.label7.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label7.ForeColor = Color.FromArgb(64, 64, 64);
      this.label7.Location = new Point(236, 37);
      this.label7.Margin = new Padding(0);
      this.label7.Name = "label7";
      this.label7.Size = new Size(74, 14);
      this.label7.TabIndex = 45;
      this.label7.Text = "Ending Date";
      this.txtInchesPerApplication.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.txtInchesPerApplication.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtInchesPerApplication.Location = new Point(246, 180);
      this.txtInchesPerApplication.Margin = new Padding(0);
      this.txtInchesPerApplication.Name = "txtInchesPerApplication";
      this.txtInchesPerApplication.Size = new Size(60, 22);
      this.txtInchesPerApplication.TabIndex = 48;
      this.label6.Font = new Font("Tahoma", 11.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label6.ForeColor = Color.Gray;
      this.label6.Location = new Point(16, 7);
      this.label6.Margin = new Padding(0);
      this.label6.Name = "label6";
      this.label6.Size = new Size(278, 18);
      this.label6.TabIndex = 43;
      this.label6.Text = "Create a uniform irrigation schedule";
      this.label4.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.ForeColor = Color.FromArgb(64, 64, 64);
      this.label4.Location = new Point(37, 180);
      this.label4.Margin = new Padding(0);
      this.label4.Name = "label4";
      this.label4.Size = new Size(200, 14);
      this.label4.TabIndex = 47;
      this.label4.Text = "Gross Inches per application";
      this.label4.TextAlign = ContentAlignment.TopRight;
      this.dteIrrigStart.Format = DateTimePickerFormat.Short;
      this.dteIrrigStart.Location = new Point(107, 36);
      this.dteIrrigStart.Margin = new Padding(0);
      this.dteIrrigStart.Name = "dteIrrigStart";
      this.dteIrrigStart.Size = new Size(101, 23);
      this.dteIrrigStart.TabIndex = 40;
      this.label3.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.ForeColor = Color.FromArgb(64, 64, 64);
      this.label3.Location = new Point(18, 37);
      this.label3.Margin = new Padding(0);
      this.label3.Name = "label3";
      this.label3.Size = new Size(80, 14);
      this.label3.TabIndex = 41;
      this.label3.Text = "Starting Date";
      this.tpCosts.AutoScroll = true;
      this.tpCosts.Controls.Add((Control) this.groupBox4);
      this.tpCosts.ImageIndex = 1;
      this.tpCosts.Location = new Point(4, 28);
      this.tpCosts.Name = "tpCosts";
      this.tpCosts.Size = new Size(484, 380);
      this.tpCosts.TabIndex = 3;
      this.tpCosts.Text = "Economic Analysis";
      this.tpCosts.UseVisualStyleBackColor = true;
      this.groupBox4.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.groupBox4.BackColor = Color.White;
      this.groupBox4.Controls.Add((Control) this.label15);
      this.groupBox4.Controls.Add((Control) this.textBox1);
      this.groupBox4.Controls.Add((Control) this.label26);
      this.groupBox4.Controls.Add((Control) this.tpInputCosts);
      this.groupBox4.Controls.Add((Control) this.txtPrice);
      this.groupBox4.Controls.Add((Control) this.label11);
      this.groupBox4.Controls.Add((Control) this.lblPriceUnits);
      this.groupBox4.Controls.Add((Control) this.label16);
      this.groupBox4.ForeColor = Color.SteelBlue;
      this.groupBox4.Location = new Point(6, 3);
      this.groupBox4.Name = "groupBox4";
      this.groupBox4.Padding = new Padding(0);
      this.groupBox4.Size = new Size(475, 374);
      this.groupBox4.TabIndex = 18;
      this.groupBox4.TabStop = false;
      this.groupBox4.Text = "Input Costs";
      this.label15.AutoSize = true;
      this.label15.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label15.ForeColor = Color.FromArgb(64, 64, 64);
      this.label15.Location = new Point(274, 53);
      this.label15.Margin = new Padding(0);
      this.label15.Name = "label15";
      this.label15.Size = new Size(40, 14);
      this.label15.TabIndex = 73;
      this.label15.Text = "Acres";
      this.label15.TextAlign = ContentAlignment.TopRight;
      this.textBox1.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.textBox1.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox1.Location = new Point(326, 51);
      this.textBox1.Margin = new Padding(0);
      this.textBox1.Name = "textBox1";
      this.textBox1.Size = new Size(67, 22);
      this.textBox1.TabIndex = 72;
      this.label26.AutoSize = true;
      this.label26.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label26.ForeColor = Color.FromArgb(64, 64, 64);
      this.label26.Location = new Point(399, 53);
      this.label26.Margin = new Padding(0);
      this.label26.Name = "label26";
      this.label26.Size = new Size(37, 14);
      this.label26.TabIndex = 71;
      this.label26.Text = "Acres";
      this.label26.TextAlign = ContentAlignment.TopRight;
      this.tpInputCosts.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.tpInputCosts.Controls.Add((Control) this.tabPage2);
      this.tpInputCosts.Controls.Add((Control) this.tabPage3);
      this.tpInputCosts.Controls.Add((Control) this.tabPage4);
      this.tpInputCosts.Controls.Add((Control) this.tabPage5);
      this.tpInputCosts.Location = new Point(6, 92);
      this.tpInputCosts.Name = "tpInputCosts";
      this.tpInputCosts.SelectedIndex = 0;
      this.tpInputCosts.Size = new Size(466, 273);
      this.tpInputCosts.TabIndex = 27;
      this.tabPage2.Controls.Add((Control) this.dgGeneralCosts);
      this.tabPage2.Location = new Point(4, 25);
      this.tabPage2.Name = "tabPage2";
      this.tabPage2.Size = new Size(458, 244);
      this.tabPage2.TabIndex = 0;
      this.tabPage2.Text = "General Costs";
      this.tabPage2.UseVisualStyleBackColor = true;
      this.dgGeneralCosts.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.dgGeneralCosts.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
      this.dgGeneralCosts.BackgroundColor = Color.White;
      this.dgGeneralCosts.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgGeneralCosts.Location = new Point(3, 3);
      this.dgGeneralCosts.Name = "dgGeneralCosts";
      this.dgGeneralCosts.Size = new Size(448, 235);
      this.dgGeneralCosts.TabIndex = 2;
      this.tabPage3.Controls.Add((Control) this.dgOperationCosts);
      this.tabPage3.Location = new Point(4, 22);
      this.tabPage3.Name = "tabPage3";
      this.tabPage3.Size = new Size(458, 247);
      this.tabPage3.TabIndex = 1;
      this.tabPage3.Text = "Operation Costs";
      this.tabPage3.UseVisualStyleBackColor = true;
      this.dgOperationCosts.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.dgOperationCosts.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
      this.dgOperationCosts.BackgroundColor = Color.White;
      this.dgOperationCosts.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgOperationCosts.Location = new Point(5, 3);
      this.dgOperationCosts.Name = "dgOperationCosts";
      this.dgOperationCosts.Size = new Size(448, (int) byte.MaxValue);
      this.dgOperationCosts.TabIndex = 3;
      this.tabPage4.Controls.Add((Control) this.dgReturns);
      this.tabPage4.Location = new Point(4, 22);
      this.tabPage4.Name = "tabPage4";
      this.tabPage4.Size = new Size(458, 247);
      this.tabPage4.TabIndex = 2;
      this.tabPage4.Text = "Returns";
      this.tabPage4.UseVisualStyleBackColor = true;
      this.dgReturns.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.dgReturns.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
      this.dgReturns.BackgroundColor = Color.White;
      this.dgReturns.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgReturns.Location = new Point(5, 3);
      this.dgReturns.Name = "dgReturns";
      this.dgReturns.Size = new Size(448, (int) byte.MaxValue);
      this.dgReturns.TabIndex = 3;
      this.tabPage5.Controls.Add((Control) this.comboBox1);
      this.tabPage5.Controls.Add((Control) this.label17);
      this.tabPage5.Controls.Add((Control) this.dgIrrigationCosts);
      this.tabPage5.Location = new Point(4, 22);
      this.tabPage5.Name = "tabPage5";
      this.tabPage5.Size = new Size(458, 247);
      this.tabPage5.TabIndex = 3;
      this.tabPage5.Text = "Irrigation Costs";
      this.tabPage5.UseVisualStyleBackColor = true;
      this.comboBox1.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.comboBox1.FormattingEnabled = true;
      this.comboBox1.Items.AddRange(new object[4]
      {
        (object) "Diesel",
        (object) "Electricity",
        (object) "Natural Gas",
        (object) "Propane"
      });
      this.comboBox1.Location = new Point(70, 3);
      this.comboBox1.Name = "comboBox1";
      this.comboBox1.Size = new Size(94, 22);
      this.comboBox1.TabIndex = 28;
      this.label17.AutoSize = true;
      this.label17.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label17.ForeColor = Color.FromArgb(64, 64, 64);
      this.label17.Location = new Point(3, 5);
      this.label17.Margin = new Padding(0);
      this.label17.Name = "label17";
      this.label17.Size = new Size(64, 14);
      this.label17.TabIndex = 27;
      this.label17.Text = "Fuel Type";
      this.label17.TextAlign = ContentAlignment.TopRight;
      this.dgIrrigationCosts.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.dgIrrigationCosts.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
      this.dgIrrigationCosts.BackgroundColor = Color.White;
      this.dgIrrigationCosts.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      this.dgIrrigationCosts.Location = new Point(5, 42);
      this.dgIrrigationCosts.Name = "dgIrrigationCosts";
      this.dgIrrigationCosts.Size = new Size(448, 210);
      this.dgIrrigationCosts.TabIndex = 3;
      this.txtPrice.BackColor = Color.FromArgb(249, 253, (int) byte.MaxValue);
      this.txtPrice.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPrice.Location = new Point(98, 51);
      this.txtPrice.Name = "txtPrice";
      this.txtPrice.Size = new Size(67, 22);
      this.txtPrice.TabIndex = 24;
      this.label11.AutoSize = true;
      this.label11.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label11.ForeColor = Color.FromArgb(64, 64, 64);
      this.label11.Location = new Point(3, 53);
      this.label11.Margin = new Padding(0);
      this.label11.Name = "label11";
      this.label11.Size = new Size(89, 14);
      this.label11.TabIndex = 25;
      this.label11.Text = "Price per Unit";
      this.label11.TextAlign = ContentAlignment.TopRight;
      this.lblPriceUnits.AutoSize = true;
      this.lblPriceUnits.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblPriceUnits.ForeColor = Color.FromArgb(64, 64, 64);
      this.lblPriceUnits.Location = new Point(168, 51);
      this.lblPriceUnits.Name = "lblPriceUnits";
      this.lblPriceUnits.Size = new Size(15, 14);
      this.lblPriceUnits.TabIndex = 23;
      this.lblPriceUnits.Text = "--";
      this.label16.BackColor = Color.Transparent;
      this.label16.ForeColor = Color.FromArgb(64, 64, 64);
      this.label16.Location = new Point(6, 21);
      this.label16.Name = "label16";
      this.label16.Size = new Size(452, 18);
      this.label16.TabIndex = 1;
      this.label16.Text = "Provide the following inputs to perform an economic analysis";
      this.AutoScaleMode = AutoScaleMode.None;
      this.Controls.Add((Control) this.tcCrops);
      this.Font = Settings.Default.FontSizedefaultUC;
      this.Name = nameof (TestControl);
      this.Size = new Size(391, 310);
      this.tcCrops.ResumeLayout(false);
      this.tpGeneral.ResumeLayout(false);
      this.groupBox3.ResumeLayout(false);
      ((ISupportInitialize) this.dgCoefficients).EndInit();
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.tpIrrigation.ResumeLayout(false);
      this.groupBox8.ResumeLayout(false);
      this.tabControl1.ResumeLayout(false);
      this.tpIrrigationEntries.ResumeLayout(false);
      ((ISupportInitialize) this.dgIrrigation).EndInit();
      this.tabPage1.ResumeLayout(false);
      this.tabPage1.PerformLayout();
      this.groupBox1.ResumeLayout(false);
      this.groupBox1.PerformLayout();
      this.tpCosts.ResumeLayout(false);
      this.groupBox4.ResumeLayout(false);
      this.groupBox4.PerformLayout();
      this.tpInputCosts.ResumeLayout(false);
      this.tabPage2.ResumeLayout(false);
      ((ISupportInitialize) this.dgGeneralCosts).EndInit();
      this.tabPage3.ResumeLayout(false);
      ((ISupportInitialize) this.dgOperationCosts).EndInit();
      this.tabPage4.ResumeLayout(false);
      ((ISupportInitialize) this.dgReturns).EndInit();
      this.tabPage5.ResumeLayout(false);
      this.tabPage5.PerformLayout();
      ((ISupportInitialize) this.dgIrrigationCosts).EndInit();
      this.ResumeLayout(false);
    }
  }
}
